DB = "rbi"

_QUESTIONS = [
    # external_sector (6 questions)
    ("t2_es_001","The Balance of Payments (BoP) is divided into:","Trade Account and Financial Account","Current Account, Capital Account, and Financial Account","Revenue Account and Capital Account","Merchandise Account and Services Account","B","BoP = Current Account (goods, services, income, transfers) + Capital Account (capital transfers, non-produced asset transactions) + Financial Account (FDI, FPI, ECB, forex reserves). A surplus in one component must be offset by a deficit in another — BoP always balances.","intl_econ","external_sector",2),
    ("t2_es_002","India's Current Account Deficit (CAD) is primarily driven by:","Services trade deficit","High merchandise deficit led by oil and gold imports","Large outflows of foreign portfolio investment","External commercial borrowing repayments","B","India runs a structural merchandise trade deficit driven by oil (energy import dependence) and gold (strong structural demand). This is partially offset by a services surplus (IT/BPO exports) and remittances. India's services account is actually a surplus — the CAD pressure comes from the goods side.","intl_econ","external_sector",2),
    ("t2_es_003","The Real Effective Exchange Rate (REER) measures:","The nominal exchange rate of rupee against a single currency (USD)","The bilateral exchange rate adjusted for gold prices","The trade-weighted nominal exchange rate adjusted for relative inflation differentials","The interest rate differential between India and its trading partners","C","REER = NEER (trade-weighted nominal rate) adjusted for relative price levels (inflation differentials). REER > 100 implies currency overvaluation vs base year; < 100 implies undervaluation. RBI publishes both 6-currency and 40-currency REER indices. NEER alone ignores competitiveness changes from inflation.","intl_econ","external_sector",2),
    ("t2_es_004","India's foreign exchange reserves are managed by:","Ministry of Finance through a sovereign wealth fund","SEBI, as they include equity and bond holdings","RBI, under the Foreign Exchange Management Act (FEMA) 1999","EXIM Bank as India's official reserve manager","C","RBI manages India's forex reserves under FEMA 1999. Reserves comprise: foreign currency assets (largest component, ~90%), gold, SDRs allocated by IMF, and reserve tranche position in IMF. India's reserves stood around $650–690 billion in early 2026, among the top 5 globally.","intl_econ","external_sector",2),
    ("t2_es_005","Foreign Portfolio Investment (FPI) differs from Foreign Direct Investment (FDI) primarily because:","FPI is regulated by RBI while FDI is regulated by SEBI","FDI involves ownership/management control (>=10% stake); FPI is passive portfolio investment","FPI can only be made in government securities; FDI is in equity only","FDI requires prior government approval; FPI does not in any case","B","FDI: >=10% stake with management control, long-term, in real/unlisted sector. FPI: <10% stake, passive, liquid, in listed securities (equity/debt). Regulation: FDI under DPIIT/FEMA; FPI under SEBI registration. Both notified to RBI. FPI flows are more volatile (hot money) than FDI.","intl_econ","external_sector",2),
    ("t2_es_006","External Commercial Borrowings (ECB) are regulated by:","SEBI under the SEBI (FPI) Regulations 2019","Ministry of Finance under the FRBM Act","RBI under FEMA, with specified end-use restrictions and eligible borrower categories","EXIM Bank as part of its trade finance mandate","C","ECB = overseas borrowings by eligible Indian entities (corporates, PSUs, NBFCs etc.) in foreign currency. Regulated by RBI under FEMA. Key rules: minimum average maturity period, end-use restrictions (cannot use for real estate investment, equity in India, repayment of rupee loans — in most tracks). Two routes: automatic and approval. Cheap foreign financing but exposes borrower to currency risk.","intl_econ","external_sector",2),
    # intl_finance (6 questions)
    ("t2_if_001","The Bank for International Settlements (BIS), which issues Basel norms through the BCBS, is headquartered in:","Washington D.C., USA","Geneva, Switzerland","Basel, Switzerland","Frankfurt, Germany","C","BIS (est. 1930) is headquartered in Basel, Switzerland — which is why global bank capital standards are called Basel norms. It serves as a bank for central banks and hosts the Basel Committee on Banking Supervision (BCBS), which produced Basel I (1988), Basel II (2004), and Basel III (2010 onwards). RBI implements Basel III in India.","intl_econ","intl_finance",2),
    ("t2_if_002","The IMF's Special Drawing Rights (SDR) basket currently comprises:","Gold, USD, EUR, GBP, JPY","USD, EUR, CNY, JPY, GBP","USD, EUR, GBP, CHF, JPY","USD, EUR, CNY, INR, GBP","B","SDR basket (post-2022 review): USD (~43.4%), EUR (~29.3%), CNY (~12.3%), JPY (~7.6%), GBP (~7.4%). Chinese Yuan (CNY/Renminbi) was added in October 2016. India's rupee is NOT an SDR basket currency. SDRs are not a currency — they are reserve assets allocated to IMF members proportional to quota, usable for exchanging freely usable currencies.","intl_econ","intl_finance",2),
    ("t2_if_003","Within the World Bank Group, concessional long-term loans to the world's poorest countries are provided by:","IBRD (International Bank for Reconstruction & Development)","IFC (International Finance Corporation)","MIGA (Multilateral Investment Guarantee Agency)","IDA (International Development Association)","D","IDA provides interest-free or near-zero interest loans and grants to countries with GNI per capita below ~$1,335. IBRD lends to middle-income and creditworthy low-income countries at near-market rates. IFC is the private sector arm (equity + loans). MIGA provides investment guarantees against non-commercial risk. India has graduated from IDA eligibility but was historically a major IDA borrower.","intl_econ","intl_finance",2),
    ("t2_if_004","The Financial Stability Board (FSB) was established in response to:","The 1997 Asian Financial Crisis","The 2001 dot-com bubble burst","The 2007-08 Global Financial Crisis","The 2013 Fed Taper Tantrum","C","FSB was established in April 2009 at the G20 London Summit to replace the Financial Stability Forum (FSF, est. 1999 after Asian crisis). FSB monitors global financial vulnerabilities, identifies Global Systemically Important Banks (G-SIBs) and Insurers (G-SIIs), and coordinates regulatory reforms. Headquartered in Basel, secretariat hosted by BIS.","intl_econ","intl_finance",2),
    ("t2_if_005","The New Development Bank (NDB), established by BRICS nations in 2014, is headquartered in:","New Delhi, India","Beijing, China","Shanghai, China","Moscow, Russia","C","NDB (Fortaleza Declaration, 2014) is headquartered in Shanghai, China. Authorised capital: $100 billion. India is a founding member and major shareholder. NDB focuses on infrastructure and sustainable development finance in emerging markets and developing countries. New members admitted since 2021: Bangladesh, UAE, Egypt, Uruguay, Ethiopia.","intl_econ","intl_finance",2),
    ("t2_if_006","IMF financial assistance is typically conditional on recipient countries agreeing to:","Pegging their currency to the USD or a currency basket","Structural adjustment / economic reform programs (IMF conditionality)","Transferring a portion of central bank reserves to IMF custody","Achieving a minimum real GDP growth target of 3% per annum","B","IMF conditionality: borrowing countries must implement agreed macroeconomic policies — fiscal consolidation, exchange rate adjustment, structural reforms — in exchange for financial support. This is central to IMF's crisis resolution role. India accessed IMF credit in 1991 BoP crisis, which triggered landmark liberalisation under Narasimha Rao/Manmohan Singh.","intl_econ","intl_finance",2),
    # nbfc_regulation (6 questions)
    ("t2_nr_001","The defining regulatory distinction between an NBFC and a commercial bank is that an NBFC:","Cannot accept any form of deposits whatsoever","Cannot accept demand deposits and is not part of the payment & settlement system","Is regulated by SEBI instead of RBI","Can only lend to other NBFCs and microfinance institutions","B","NBFCs cannot: (1) accept demand deposits (current/savings accounts payable on demand), (2) issue cheques drawn on themselves, (3) access DICGC deposit insurance. Some NBFC categories (NBFC-D) can accept public time deposits (fixed deposits). CRR/SLR norms do not apply to most NBFCs. These three exclusions define the NBFC-bank regulatory difference.","rbi_banking","nbfc_regulation",2),
    ("t2_nr_002","Under RBI's Scale-Based Regulation (SBR) for NBFCs, the Upper Layer consists of:","All NBFCs with total assets exceeding Rs 10,000 crore","Specifically identified NBFCs by RBI using a scoring methodology — typically top ~10","All deposit-taking NBFCs irrespective of asset size","NBFCs operating in more than 5 states","B","SBR (effective Oct 2022) layers: Base Layer (small NBFCs, <Rs 1000 cr ND), Middle Layer (>=Rs 1000 cr ND + all NBFC-D + IFCs + HFCs etc.), Upper Layer (top ~10 by RBI scoring — near-bank regulation applies: CRAR, large exposure limits), Top Layer (empty by design). Upper Layer != simply the largest — it is scored on size + interconnectedness + complexity.","rbi_banking","nbfc_regulation",2),
    ("t2_nr_003","Regulation of Housing Finance Companies (HFCs) was transferred from NHB to RBI in:","2016 — following demonetisation","2019 — via the National Housing Bank (Amendment) Act","2021 — following IL&FS systemic crisis resolution","2023 — as part of HDFC-HDFC Bank merger regulatory harmonisation","B","The NHB (Amendment) Act 2019 transferred HFC registration and regulation to RBI. NHB continues as a refinance institution for housing. The transfer was accelerated by the IL&FS/DHFL crisis (2018-19) that exposed regulatory arbitrage and gaps in NBFC/HFC oversight. HFCs now fall under RBI's SBR framework.","rbi_banking","nbfc_regulation",2),
    ("t2_nr_004","NBFC-Peer to Peer (P2P) lending platforms are characterised as:","Banks under the Banking Regulation Act 1949","NBFC intermediaries regulated by RBI — they connect borrowers and lenders but do not lend from their own books","Payment System Operators under the Payment and Settlement Systems Act","Unregulated fintech platforms under Ministry of Corporate Affairs","B","P2P platforms classified as NBFC-P2P under RBI's 2017 Master Directions. They are pure intermediaries — cannot use their own funds to lend. Key limits: aggregate lender exposure <= Rs 50 lakh across all P2P platforms; max loan tenure 36 months; platforms cannot guarantee returns or provide credit enhancement.","rbi_banking","nbfc_regulation",2),
    ("t2_nr_005","The Account Aggregator (AA) framework in India is primarily designed to:","Aggregate non-performing assets of banks for centralised RBI resolution","Enable consent-based, encrypted sharing of financial data between regulated entities","Consolidate foreign exchange accounts of NRIs under one RBI portal","Track GST compliance across multiple business entities via GSTN","B","AAs are NBFC-AAs regulated by RBI. They act as data intermediaries — enabling consent-based sharing of financial information from Financial Information Providers (FIPs: banks, NBFCs, MFs, insurers) to Financial Information Users (FIUs: lenders, wealth managers). AAs cannot read or read or store the data — it flows encrypted. Enables instant credit underwriting and digital lending.","rbi_banking","nbfc_regulation",2),
    ("t2_nr_006","RBI's minimum Net Owned Funds (NOF) requirement for registering a new NBFC (general category) was revised to _____ effective 2021:","Rs 2 crore","Rs 5 crore","Rs 10 crore","Rs 25 crore","C","RBI raised the minimum NOF for NBFC registration from Rs 2 crore to Rs 10 crore in October 2021 (for new registrations). Existing NBFCs with Rs 2-Rs 10 crore NOF were given a glide-path. Intermediary NBFCs like NBFC-AA and NBFC-P2P have separate lower thresholds (Rs 2 crore). The hike ensures only adequately capitalised entities enter the NBFC space.","rbi_banking","nbfc_regulation",2),
]


def run(conn):
    conn.executemany(
        "INSERT OR IGNORE INTO rbi_questions "
        "(id,question,option_a,option_b,option_c,option_d,correct_option,explanation,subject,topic,tier) "
        "VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        _QUESTIONS,
    )
    conn.commit()
