"""m052 — Seed upsc_gs.db: reference tables + all questions (essay + ethics)"""

DB = "upsc_gs"


def run(conn):
    # essay_frameworks: 6 rows
    conn.executemany(
        "INSERT OR IGNORE INTO essay_frameworks (framework_id, framework_name, slots_json, best_for_themes, typical_sections, is_active, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
        [
        ('PESTLE', 'PESTLE Analysis', '[{"slot": "P", "label": "Political"}, {"slot": "E", "label": "Economic"}, {"slot": "S", "label": "Social"}, {"slot": "T", "label": "Technological"}, {"slot": "L", "label": "Legal"}, {"slot": "E2", "label": "Environmental"}]', '["governance", "economy", "technology", "digital_inequality", "federalism"]', '["B"]', 1, '2026-06-21 13:30:49'),
        ('SPIDER', 'SPIDER Framework', '[{"slot": "S", "label": "Social"}, {"slot": "P", "label": "Political"}, {"slot": "I", "label": "Institutional"}, {"slot": "D", "label": "Developmental"}, {"slot": "E", "label": "Economic"}, {"slot": "R", "label": "Rights"}]', '["gender_justice", "development_inequality", "social_justice", "media_democracy"]', '["B"]', 1, '2026-06-21 13:30:49'),
        ('IDEA', 'IDEA Framework', '[{"slot": "I", "label": "Ideational"}, {"slot": "D", "label": "Dialectical"}, {"slot": "E", "label": "Ethical"}, {"slot": "A", "label": "Aspirational"}]', '["values_ethics", "philosophy", "democracy", "science_aspiration"]', '["A"]', 1, '2026-06-21 13:30:49'),
        ('PPF', 'Past-Present-Future', '[{"slot": "PAST", "label": "Historical"}, {"slot": "PRESENT", "label": "Contemporary"}, {"slot": "FUTURE", "label": "Aspirational"}]', '["nature_environment", "philosophy", "geopolitics", "education"]', '["A", "B"]', 1, '2026-06-21 13:30:49'),
        ('INDIVIDUAL_SOCIETY', 'Individual and Society', '[{"slot": "I", "label": "Individual"}, {"slot": "S", "label": "Society"}]', '["values_ethics", "philosophy", "social_justice"]', '["A"]', 1, '2026-06-21 13:30:49'),
        ('CUSTOM', 'Custom Framework', '[]', '[]', '["A", "B"]', 1, '2026-06-21 13:30:49'),
        ]
    )

    # essay_hook_types: 6 rows
    conn.executemany(
        "INSERT OR IGNORE INTO essay_hook_types (hook_type_id, label, description, example_template, best_for_themes, is_active) VALUES (?, ?, ?, ?, ?, ?)",
        [
        ('QUOTE', 'Quotation', 'Open with a direct quote from a thinker, leader, or literary figure.', 'As [THINKER] once said, "[QUOTE]"', '["values_ethics", "philosophy", "governance", "social_justice"]', 1),
        ('DATA', 'Statistic / Data Point', 'Open with a striking number or empirical finding.', 'According to [SOURCE], [STATISTIC] — a figure that demands urgent reflection.', '["technology", "economy", "gender_justice", "education"]', 1),
        ('HISTORICAL_FACT', 'Historical Fact', 'Open with a pivotal historical moment or turning point.', 'When [EVENT] in [YEAR], it revealed [INSIGHT] that resonates to this day.', '["governance", "values_ethics", "nature_environment", "geopolitics"]', 1),
        ('CONTEMPORARY', 'Contemporary Event', 'Open with a recent current affairs event or development.', 'In [YEAR], [EVENT] forced the world to confront [THEME] in ways previously unimagined.', '["technology", "economy", "governance", "gender_justice"]', 1),
        ('LITERARY_REF', 'Literary / Philosophical Reference', 'Open by invoking a poem, parable, myth, or philosophical text.', '[WORK] by [AUTHOR] begins with [REFERENCE] — a metaphor that illuminates our theme.', '["values_ethics", "philosophy", "nature_environment", "education"]', 1),
        ('RHETORICAL_Q', 'Rhetorical Question', "Open with a provocative question that frames the essay's central tension.", 'What does it mean to [ACTION] in an age when [PARADOX]?', '["values_ethics", "philosophy", "technology", "democracy"]', 1),
        ]
    )

    # essay_theme_analysis: 7 rows
    conn.executemany(
        "INSERT OR IGNORE INTO essay_theme_analysis (theme_tag, theme_label, frequency_count, typical_section, year_appearances, example_questions, fy26_ca_hook, trend, probability_2026, last_updated) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [
        ('values_ethics', 'Philosophy of Values & Ethics', 12, 'A', '[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]', '[{"year": 2024, "section": "A", "prompt": "There is no path to happiness; happiness is the path."}, {"year": 2025, "section": "A", "prompt": "Truth knows no color."}]', "India's Viksit Bharat 2047 discourse raises questions about what kind of nation we aspire to be — material prosperity alone or moral civilizational rise.", 'stable', 'high', '2026-06-21 13:30:49'),
        ('technology', 'Technology: Promise, Peril, Displacement', 9, 'both', '[2015, 2017, 2018, 2019, 2020, 2022, 2023, 2024, 2025]', '[{"year": 2024, "section": "B", "prompt": "Social media is triggering the Fear of Missing Out amongst the youth."}]', "Generative AI adoption (ChatGPT, Gemini), India's Digital Public Infrastructure (UPI, ONDC, DPDP Act 2023), and Operation Sindoor drone warfare signal that tech-society tension is unavoidable in 2026.", 'rising', 'high', '2026-06-21 13:30:49'),
        ('gender_justice', 'Gender Justice & Women Empowerment', 7, 'B', '[2014, 2016, 2018, 2019, 2021, 2022, 2024]', '[{"year": 2022, "section": "B", "prompt": "The most important lesson in life is \'never give up.\'"}]', "Women's Reservation Act 2023 (33% seats in Lok Sabha/Assemblies) awaits delimitation trigger; Nari Shakti Vandan Adhiniyam implementation debate ongoing.", 'stable', 'medium', '2026-06-21 13:30:49'),
        ('education', 'Education: Purpose, Reform, Values', 6, 'both', '[2015, 2017, 2019, 2021, 2023, 2024]', '[{"year": 2024, "section": "A", "prompt": "The empires of the future will be the empires of the mind."}]', 'NEP 2020 full implementation ongoing; IIT/NIRF rankings and employability gap debate; AI in classrooms raises question: what is education FOR?', 'stable', 'medium', '2026-06-21 13:30:49'),
        ('economy', 'Economy: Growth, Inequality, Inclusion', 6, 'B', '[2014, 2016, 2018, 2020, 2022, 2025]', '[{"year": 2025, "section": "B", "prompt": "Contentment is natural wealth; luxury is artificial poverty."}]', 'India surpassed Japan as 4th largest economy; yet Oxford Multidimensional Poverty Index shows 230M still poor. Growth-inequality paradox is live.', 'stable', 'medium', '2026-06-21 13:30:49'),
        ('governance', 'Governance: Federalism, Institutions', 5, 'B', '[2016, 2018, 2020, 2022, 2024]', '[{"year": 2024, "section": "B", "prompt": "Nearly all men can stand adversity, but to test a man\'s character, give him power."}]', 'One Nation One Election debate; SC vs. executive tensions (collegium, electoral bonds); cooperative vs. competitive federalism in GST council.', 'stable', 'medium', '2026-06-21 13:30:49'),
        ('nature_environment', 'Nature, Environment & Civilization', 5, 'both', '[2015, 2018, 2020, 2022, 2024]', '[{"year": 2024, "section": "A", "prompt": "Forest precedes civilization and the desert follows them."}]', "COP29 Baku pledges vs. India's coal dependency; heatwave deaths (2024 peak: 50.7°C in Rajasthan); biodiversity loss report (IPBES 2024).", 'rising', 'high', '2026-06-21 13:30:49'),
        ]
    )

    # gs4_thinkers: 15 rows
    conn.executemany(
        "INSERT OR IGNORE INTO gs4_thinkers (thinker_id, name, era, school_of_thought, key_works, core_concepts, upsc_relevance_score, most_cited_quote, typical_question_angle, years_appeared, concept_links, indian_governance_application, common_mistake) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [
        ('thinker_gandhi', 'Mahatma Gandhi', '20th century', 'Indian Political Philosophy / Non-violence', '["Hind Swaraj", "My Experiments with Truth", "Sarvodaya"]', '["Satyagraha", "Ahimsa", "Trusteeship", "means-ends inseparability", "Swaraj", "Gram Swaraj"]', 0.97, 'The means are the end in miniature.', 'Means-ends inseparability; civil servant duty vs conscience; anti-corruption stance', '[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]', '["gs4_c_integrity", "gs4_c_honesty", "gs4_c_public_service_values"]', 'Trusteeship model for public resources; non-violence in conflict resolution; panchayati raj foundations', 'Conflating Satyagraha with passive resistance — it is active moral resistance, not inaction'),
        ('thinker_vivekananda', 'Swami Vivekananda', '19th-20th century', 'Vedanta / Indian Spirituality', '["Raja Yoga", "Karma Yoga", "Jnana Yoga", "Chicago Address 1893"]', '["service as worship (Daridra Narayana)", "character as foundation", "inner strength", "practical Vedanta", "strength-based ethics"]', 0.93, 'Education is the manifestation of the perfection already in man.', 'Public service as worship; character-building for civil servants; human dignity', '[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]', '["gs4_c_empathy", "gs4_c_public_service_values", "gs4_c_compassion"]', 'Civil servant as servant-leader; RTE: education for character not just livelihood; welfare delivery with dignity', 'Treating him as only religious thinker — UPSC asks for governance/administrative ethics angle'),
        ('thinker_kant', 'Immanuel Kant', '18th century', 'Deontological Ethics', '["Groundwork of the Metaphysics of Morals", "Critique of Pure Reason", "Critique of Practical Reason"]', '["Categorical Imperative", "duty-based ethics", "universalisability", "dignity of persons as ends", "good will"]', 0.9, 'Act only according to that maxim whereby you can at the same time will that it should become a universal law.', 'Duty over consequences; rule-based decision making; civil servant as duty-bound agent', '[2013, 2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022, 2023, 2024]', '["gs4_c_integrity", "gs4_c_honesty", "gs4_c_rule_of_law"]', 'Categorical Imperative as test for policy universalisation; treating citizens as ends (not means) in welfare delivery; Rule of Law', 'Stating Categorical Imperative without applying it — must demonstrate universalisation test in answer'),
        ('thinker_aristotle', 'Aristotle', 'Ancient Greece (384-322 BCE)', 'Virtue Ethics', '["Nicomachean Ethics", "Politics", "Rhetoric"]', '["Virtue Ethics", "eudaimonia (flourishing)", "phronesis (practical wisdom)", "the Golden Mean", "moral habituation"]', 0.88, 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', 'Character formation; practical wisdom in decision-making; virtuous civil servant', '[2014, 2015, 2016, 2018, 2019, 2020, 2021, 2022, 2023, 2024]', '["gs4_c_integrity", "gs4_c_emotional_intelligence", "gs4_c_compassion"]', 'Golden Mean in policy: balance development vs environment; Phronesis for IAS officer judgment in field; virtue habituation in training', 'Eudaimonia ≠ happiness — it is human flourishing through virtuous activity, not pleasure'),
        ('thinker_ambedkar', 'B.R. Ambedkar', '20th century', 'Constitutional Morality / Social Justice', '["Annihilation of Caste", "The Buddha and His Dhamma", "Waiting for a Visa"]', '["Constitutional morality over social morality", "dignity of the individual", "social justice", "anti-caste ethics", "self-respect"]', 0.88, 'Constitutional morality is not a natural sentiment. It has to be cultivated.', 'Constitutional morality vs prevailing social norms; dignity in welfare delivery; reservation ethics', '[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]', '["gs4_c_social_justice", "gs4_c_human_rights", "gs4_c_impartiality"]', 'Civil servant duty to uphold constitutional morality even against local social pressure; SC/ST atrocity cases; welfare delivery with dignity', 'Limiting him to reservation debate — his constitutional morality concept applies to all governance ethics questions'),
        ('thinker_bentham', 'Jeremy Bentham', '18th-19th century', 'Utilitarianism', '["Introduction to Principles of Morals and Legislation", "The Panopticon Writings"]', '["Utility principle", "felicific calculus", "greatest happiness of greatest number", "hedonistic calculus"]', 0.82, 'The greatest good for the greatest number.', 'Consequentialist policy justification; welfare maximisation; trolley-problem type dilemmas', '[2014, 2016, 2017, 2019, 2020, 2021, 2022, 2023]', '["gs4_c_utilitarian_ethics", "gs4_c_public_interest", "gs4_c_welfare"]', 'GDP growth vs inequality trade-offs; displacement for development projects; drug policy harm reduction', 'Ignoring minority rights — UPSC cases often test limits of majority utility; must flag this limitation'),
        ('thinker_mill', 'John Stuart Mill', '19th century', 'Liberal Utilitarianism', '["Utilitarianism", "On Liberty", "The Subjection of Women"]', '["higher and lower pleasures", "harm principle", "individual liberty", "representative government", "quality over quantity of pleasure"]', 0.8, 'The liberty of the individual must be thus far limited; he must not make himself a nuisance to other people.', 'Harm principle in regulatory ethics; civil servant intervention boundaries; press freedom', '[2015, 2017, 2018, 2020, 2021, 2022, 2023]', '["gs4_c_utilitarian_ethics", "gs4_c_human_rights", "gs4_c_freedom"]', 'Harm principle: when state can restrict freedom (sedition, social media regulation); quality pleasures: education over opium — drug policy', 'Conflating Mill with Bentham — Mill adds qualitative dimension (higher pleasures) and individual rights protection'),
        ('thinker_rawls', 'John Rawls', '20th century', 'Liberal Egalitarianism / Social Contract', '["A Theory of Justice", "Political Liberalism"]', '["Veil of Ignorance", "Original Position", "Difference Principle", "lexical ordering of principles", "justice as fairness"]', 0.85, 'Justice is the first virtue of social institutions.', 'Reservation policy; progressive taxation; welfare state design; impartial policymaking', '[2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]', '["gs4_c_social_justice", "gs4_c_impartiality", "gs4_c_welfare"]', 'Veil of Ignorance as impartiality test for civil servants; Difference Principle as justification for reservation; 15th Finance Commission devolution', "Stopping at 'veil of ignorance' — must explain what principles people would choose behind it (liberty + difference principle)"),
        ('thinker_plato', 'Plato', 'Ancient Greece (428-348 BCE)', 'Idealism / Philosopher-King Theory', '["The Republic", "The Laws", "Apology"]', '["Philosopher-King", "cardinal virtues (wisdom/courage/temperance/justice)", "tripartite soul", "Forms (ideal types)", "justice as harmony"]', 0.75, 'Until philosophers rule as kings, cities will have no rest from evil.', 'Ideal civil servant qualities; virtue-based governance; role of wisdom in administration', '[2014, 2015, 2016, 2017, 2019, 2021, 2023]', '["gs4_c_integrity", "gs4_c_wisdom", "gs4_c_justice"]', 'Four cardinal virtues → IAS officer qualities; philosopher-king → technocrat role in governance; justice as societal harmony', 'Philosopher-King as anti-democratic — UPSC wants you to extract virtue framework, not the elitist political theory'),
        ('thinker_confucius', 'Confucius', 'Ancient China (551-479 BCE)', 'Confucianism / Relational Ethics', '["Analects"]', '["Ren (benevolence/humaneness)", "Li (ritual propriety)", "Yi (righteousness)", "filial piety", "rectification of names"]', 0.72, 'To know what is right and not do it is the worst cowardice.', 'Relational ethics in administration; community duty; governance through moral example', '[2016, 2018, 2020, 2022, 2023]', '["gs4_c_integrity", "gs4_c_public_service_values", "gs4_c_compassion"]', 'Ren as empathetic governance; Li as procedural propriety in administration; moral leadership model for officers', 'Treating Confucius as purely social thinker — his governance ethics are highly applicable to administrative behaviour'),
        ('thinker_aurobindo', 'Sri Aurobindo', '19th-20th century', 'Integral Philosophy / Indian Idealism', '["The Life Divine", "Essays on the Gita", "The Synthesis of Yoga"]', '["Integral human development", "inner transformation as governance basis", "divine in humanity", "yogic statecraft"]', 0.68, 'All life is yoga.', 'Inner transformation of civil servant; spiritual dimension of public service; holistic development', '[2016, 2019, 2021, 2023]', '["gs4_c_empathy", "gs4_c_public_service_values"]', 'Inner transformation → incorruptible civil servant; integral human development as policy goal beyond GDP', 'Appearing too abstract — must ground in concrete governance example to score'),
        ('thinker_kohlberg', 'Lawrence Kohlberg', '20th century', 'Moral Development Psychology', '["Essays on Moral Development"]', '["6 stages of moral development", "pre-conventional / conventional / post-conventional", "principled moral reasoning", "Heinz dilemma"]', 0.78, 'Moral development is not just about knowing what is right, but about being motivated to act on it.', 'Moral development of civil servant over career; post-conventional reasoning in dilemma resolution', '[2015, 2017, 2019, 2020, 2021, 2022, 2023, 2024]', '["gs4_c_emotional_intelligence", "gs4_c_integrity", "gs4_c_conscience"]', '6-stage model: IAS officer expected at Stage 5-6 (social contract / universal principles); training implications; whistleblowing as Stage 6', 'Stopping at naming the stages — UPSC wants application of a specific stage to the scenario given'),
        ('thinker_kautilya', 'Kautilya (Chanakya)', 'Ancient India (350-275 BCE)', 'Realist Political Philosophy / Arthashastra Tradition', '["Arthashastra"]', '["Rajadharma (king\'s duty)", "Matsya Nyaya (big fish eats small)", "Dandaniti (science of punishment)", "spy system", "welfare state (Praja Sukhe Sukham Rajnah)"]', 0.82, "In the happiness of his subjects lies the king's happiness; in their welfare his welfare.", 'Rajadharma for civil servants; anti-corruption vigilance; accountability mechanisms', '[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]', '["gs4_c_accountability", "gs4_c_public_interest", "gs4_c_integrity"]', 'Arthashastra surveillance → RTI/Lokpal; Rajadharma → fundamental duties of civil servant; Dandaniti → proportionality in punishment', "Kautilya ≠ Machiavelli — Kautilya's realism is welfare-grounded; Machiavelli is power-only. Conflating both in answers loses marks"),
        ('thinker_machiavelli', 'Niccolò Machiavelli', '15th-16th century', 'Political Realism', '["The Prince", "Discourses on Livy"]', '["ends justify means (realpolitik)", "Virtu and Fortuna", "practical over idealistic governance", "separation of ethics from politics"]', 0.7, 'The end justifies the means.', 'Contrasting point to Kant/Gandhi (ends vs means debate); limits of consequentialist governance', '[2015, 2017, 2019, 2021, 2022]', '["gs4_c_utilitarian_ethics", "gs4_c_integrity"]', "Foil for Gandhi's means-ends inseparability argument; realpolitik in foreign policy IR cases; BUT UPSC expects civil servants to reject Machiavellianism", 'Citing Machiavelli approvingly — in UPSC GS4 context, he is typically the position-to-be-rejected, not endorsed'),
        ('thinker_nussbaum', 'Martha Nussbaum', '20th-21st century', 'Capabilities Approach / Feminist Ethics', '["Creating Capabilities", "Upheavals of Thought", "Sex and Social Justice"]', '["Capabilities Approach (with Sen)", "central human capabilities", "emotions in ethics (moral emotions)", "dignity of marginalised", "narrative imagination"]', 0.73, 'Narrative imagination is the ability to think what it might be like to be in the shoes of a person different from oneself.', 'Empathy in administration; welfare beyond GDP; gender justice; marginalised group dignity', '[2018, 2019, 2021, 2022, 2023, 2024]', '["gs4_c_empathy", "gs4_c_social_justice", "gs4_c_compassion", "gs4_c_human_rights"]', 'Capabilities list as welfare policy checklist; moral emotions (compassion/anger) as guides in atrocity cases; POCSO/PWDV Act administration', 'Conflating with Amartya Sen — both use Capabilities Approach but Nussbaum adds specific capability list and feminist/emotional dimension'),
        ]
    )

    # essay_questions: 36 rows
    conn.executemany(
        "INSERT OR IGNORE INTO essay_questions (essay_id, prompt, section, theme_tag, hook_type_id, framework_id, word_limit, marks, year_appeared, content_type, generation_year, difficulty, is_high_probability, backing_note, source_proposal_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [
        ('pyq_2024_a1', 'Forest precedes civilization and the desert follows them.', 'A', 'nature_environment', 'LITERARY_REF', 'PPF', None, None, 2024, 'pyq', 2024, 'medium', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2024_a2', 'The empires of the future will be the empires of the mind.', 'A', 'education', 'QUOTE', 'IDEA', None, None, 2024, 'pyq', 2024, 'medium', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2024_a3', 'There is no path to happiness; happiness is the path.', 'A', 'values_ethics', 'QUOTE', 'IDEA', None, None, 2024, 'pyq', 2024, 'easy', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2024_a4', 'The doubter is a true man of science.', 'A', 'values_ethics', 'HISTORICAL_FACT', 'INDIVIDUAL_SOCIETY', None, None, 2024, 'pyq', 2024, 'medium', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2024_b1', 'Social media is triggering the Fear of Missing Out amongst the youth, causing depression and loneliness.', 'B', 'technology', 'DATA', 'PESTLE', None, None, 2024, 'pyq', 2024, 'easy', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2024_b2', "Nearly all men can stand adversity, but to test a man's character, give him power.", 'B', 'governance', 'QUOTE', 'INDIVIDUAL_SOCIETY', None, None, 2024, 'pyq', 2024, 'medium', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2024_b3', 'All ideas having large consequences are always simple.', 'B', 'values_ethics', 'HISTORICAL_FACT', 'IDEA', None, None, 2024, 'pyq', 2024, 'hard', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2024_b4', 'The cost of being wrong is less than the cost of doing nothing.', 'B', 'governance', 'CONTEMPORARY', 'PESTLE', None, None, 2024, 'pyq', 2024, 'medium', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2025_a1', 'Truth knows no color.', 'A', 'values_ethics', 'HISTORICAL_FACT', 'IDEA', None, None, 2025, 'pyq', 2025, 'medium', 0, '2025 anomaly: all 8 questions philosophical. Section B did not follow contemporary pattern.', None, '2026-06-21 13:30:49'),
        ('pyq_2025_a2', 'The supreme art of war is to subdue the enemy without fighting.', 'A', 'values_ethics', 'QUOTE', 'IDEA', None, None, 2025, 'pyq', 2025, 'hard', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2025_a3', 'Thought finds a world and creates one also.', 'A', 'values_ethics', 'LITERARY_REF', 'PPF', None, None, 2025, 'pyq', 2025, 'hard', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2025_a4', 'Best lessons are learnt through bitter experiences.', 'A', 'values_ethics', 'HISTORICAL_FACT', 'INDIVIDUAL_SOCIETY', None, None, 2025, 'pyq', 2025, 'easy', 0, None, None, '2026-06-21 13:30:49'),
        ('pyq_2025_b1', 'Muddy water is best cleared by leaving it alone.', 'B', 'values_ethics', 'LITERARY_REF', 'IDEA', None, None, 2025, 'pyq', 2025, 'hard', 0, 'Taoist philosophy — ecological metaphor', None, '2026-06-21 13:30:49'),
        ('pyq_2025_b2', 'The years teach much which the days never know.', 'B', 'values_ethics', 'QUOTE', 'PPF', None, None, 2025, 'pyq', 2025, 'easy', 0, 'Emerson quote', None, '2026-06-21 13:30:49'),
        ('pyq_2025_b3', 'It is best to see life as a journey, not as a destination.', 'B', 'values_ethics', 'LITERARY_REF', 'IDEA', None, None, 2025, 'pyq', 2025, 'easy', 0, 'Buddhist and Upanishadic resonance', None, '2026-06-21 13:30:49'),
        ('pyq_2025_b4', 'Contentment is natural wealth; luxury is artificial poverty.', 'B', 'economy', 'QUOTE', 'PESTLE', None, None, 2025, 'pyq', 2025, 'medium', 0, 'Socrates + Gandhi dual citation', None, '2026-06-21 13:30:49'),
        ('prac_2026_01', 'Power reveals character — examine through democratic institutions, bureaucracy, and leadership.', 'A', 'values_ethics', 'QUOTE', 'IDEA', None, None, None, 'practice', 2026, 'medium', 0, 'Values+power theme has appeared 12 times in 10 years. Appears in both sections. The 2024 paper itself used a variant of this Lincoln quote in Section B — expect it to return in Section A in philosophical framing.', None, '2026-06-21 13:30:49'),
        ('prac_2026_02', 'What is best for the individual is not always best for society — where does virtue end and responsibility begin?', 'A', 'values_ethics', 'HISTORICAL_FACT', 'INDIVIDUAL_SOCIETY', None, None, None, 'practice', 2026, 'medium', 0, 'Ethics-social contract framing bridges Section A philosophy and Section B governance. High frequency in abstract essay tradition.', None, '2026-06-21 13:30:49'),
        ('prac_2026_03', 'Technology has not replaced our search for meaning — it has outsourced it.', 'A', 'technology', 'DATA', 'PESTLE', None, None, None, 'practice', 2026, 'hard', 0, 'Generative AI and social media algorithms as meaning-makers — a 2026 CA hook that bridges values and technology themes.', None, '2026-06-21 13:30:49'),
        ('prac_2026_04', 'When we lose a forest, we lose the grammar of civilization.', 'A', 'nature_environment', 'LITERARY_REF', 'PPF', None, None, None, 'practice', 2026, 'medium', 0, 'Nature-civilization theme rising (trend: rising). 2024 PYQ opened the same theme — Section A is likely to avoid direct repetition but the philosophical framing opens adjacent ground.', None, '2026-06-21 13:30:49'),
        ('prac_2026_05', 'In an age of algorithms, the doubter is the last free man.', 'A', 'values_ethics', 'RHETORICAL_Q', 'IDEA', None, None, None, 'practice', 2026, 'hard', 0, "Epistemic freedom under information overload. Connects to 2024 PYQ 'The doubter is a true man of science' — a philosophical evolution of that prompt toward AI-era context.", None, '2026-06-21 13:30:49'),
        ('prac_2026_06', 'Wantlessness is Utopian; materialism a chimera — the sustainable life lies between.', 'A', 'values_ethics', 'QUOTE', 'PESTLE', None, None, None, 'practice', 2026, 'hard', 0, "Gandhi's philosophy meets SDG targets. Economy-ethics intersection that could appear in Section A (philosophical) or Section B (policy). Medium probability.", None, '2026-06-21 13:30:49'),
        ('prac_2026_07', "Women's Reservation Act gives women seats — but does it give them power?", 'B', 'gender_justice', 'DATA', 'SPIDER', None, None, None, 'practice', 2026, 'medium', 1, "Women's Reservation Act 2023 awaits delimitation trigger for implementation. Gap between formal representation and substantive power is a live governance debate — high CA resonance in 2026.", None, '2026-06-21 13:30:49'),
        ('prac_2026_08', 'Can India become Viksit Bharat 2047 while 300 million remain in poverty?', 'B', 'economy', 'DATA', 'PESTLE', None, None, None, 'practice', 2026, 'medium', 1, "Viksit Bharat 2047 is the government's flagship aspirational narrative. Oxford MPI data on 230M poor + India's 4th largest economy ranking creates the central tension for 2026.", None, '2026-06-21 13:30:49'),
        ('prac_2026_09', "AI is democracy's greatest promise and most dangerous threat — simultaneously.", 'B', 'technology', 'CONTEMPORARY', 'PESTLE', None, None, None, 'practice', 2026, 'hard', 1, 'Deepfakes in 2024 US/India elections, AI-generated misinformation, vs. AI for voter access and grievance redressal. DPDP Act 2023 and AI governance debate makes this a 2026 live issue.', None, '2026-06-21 13:30:49'),
        ('prac_2026_10', 'Climate change is not an environmental problem — it is a civilizational test.', 'A', 'nature_environment', 'DATA', 'SPIDER', None, None, None, 'practice', 2026, 'medium', 1, 'COP29 Baku (2024) pledges vs. coal dependency; 2024 heatwave deaths; IPBES 2024 biodiversity report. Rising theme with dual-section flexibility — high probability.', None, '2026-06-21 13:30:49'),
        ('prac_2026_11', "Cooperative federalism is India's constitutional grammar — competitive politics is the language spoken.", 'B', 'governance', 'HISTORICAL_FACT', 'PESTLE', None, None, None, 'practice', 2026, 'hard', 1, 'GST Council friction, One Nation One Election debate, and Centre-state resource allocation tensions are live. High CA relevance for 2026 essay paper.', None, '2026-06-21 13:30:49'),
        ('prac_2026_12', 'In a world of tariff walls, economic self-reliance is not protectionism — it is survival.', 'B', 'economy', 'CONTEMPORARY', 'PESTLE', None, None, None, 'practice', 2026, 'hard', 1, "US-China tariff war 2025, India's PLI scheme, Atmanirbhar Bharat reframing. Trade sovereignty debate elevated by Operation Sindoor and India's strategic positioning.", None, '2026-06-21 13:30:49'),
        ('prac_2026_13', "A nation's right to protect its citizens can never fully justify the violence it unleashes in their name.", 'A', 'values_ethics', 'HISTORICAL_FACT', 'IDEA', None, None, None, 'practice', 2026, 'hard', 1, 'Operation Sindoor (May 2026) and just war theory debate. Security vs. ethics of force is a perennial UPSC theme elevated to high probability by the most significant CA event of 2026.', None, '2026-06-21 13:30:49'),
        ('prac_2026_14', 'An institution that loses its integrity cannot restore it by reforming its rankings.', 'B', 'education', 'CONTEMPORARY', 'IDEA', None, None, None, 'practice', 2026, 'medium', 0, 'NIRF rankings pressure on universities vs. substantive quality. UGC NET paper leak 2024 and examination integrity debate make this contemporary.', None, '2026-06-21 13:30:49'),
        ('prac_2026_15', 'In a post-truth world, a free press is not a luxury of democracy — it is its precondition.', 'B', 'governance', 'QUOTE', 'SPIDER', None, None, None, 'practice', 2026, 'medium', 0, "India's press freedom ranking (World Press Freedom Index 2024: 159/180). AI-generated misinformation and the role of independent media as democratic infrastructure.", None, '2026-06-21 13:30:49'),
        ('prac_2026_16', "Space exploration is not a flight from earthly problems — it is a civilized state's highest ambition.", 'A', 'values_ethics', 'CONTEMPORARY', 'PPF', None, None, None, 'practice', 2026, 'medium', 0, "Chandrayaan-3 success (2023) and ISRO's upcoming missions. Science as national aspiration — Section A philosophical framing of India's space ambition.", None, '2026-06-21 13:30:49'),
        ('prac_2026_17', 'A society that has more justice is a society that needs less charity.', 'B', 'economy', 'QUOTE', 'SPIDER', None, None, None, 'practice', 2026, 'medium', 0, "MLK quote applied to India's welfare vs. rights-based approach debate. PM-KISAN, MGNREGA, and the shift from charity to entitlement framing.", None, '2026-06-21 13:30:49'),
        ('prac_2026_18', 'The digital economy promised to be the great leveller — the divide it created is deeper than the one it closed.', 'B', 'technology', 'DATA', 'PESTLE', None, None, None, 'practice', 2026, 'medium', 0, "Digital divide data: 900M internet users vs. 400M without access. Gig economy exploitation, platform monopolies, and DPDP Act's distributional impact.", None, '2026-06-21 13:30:49'),
        ('prac_2026_19', "India's Non-Alignment was born of one world order — today's multipolar chaos demands a new strategic doctrine.", 'B', 'governance', 'HISTORICAL_FACT', 'PESTLE', None, None, None, 'practice', 2026, 'hard', 0, "India's strategic autonomy in the Russia-Ukraine war, Israel-Gaza, and US-China rivalry. Non-Alignment 2.0 concept and India's G20 presidency legacy.", None, '2026-06-21 13:30:49'),
        ('prac_2026_20', 'Simplicity is the ultimate sophistication — but who still dares to choose less in the age of AI?', 'A', 'values_ethics', 'QUOTE', 'IDEA', None, None, None, 'practice', 2026, 'medium', 0, 'da Vinci quote repurposed for AI age. Values-modernity tension with philosophical depth — classic Section A framing. Connects to minimalism, attention economy, and Gandhian simplicity.', None, '2026-06-21 13:30:49'),
        ]
    )

    # ethics_questions: 93 rows
    conn.executemany(
        "INSERT OR IGNORE INTO ethics_questions (question_id, paper_year, paper_id, section, question_type, question_text, case_preamble, sub_part, marks, content_type, concept_tags, thinker_tags, framework_hint, sequence_order, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        [
        ('ethics_pyq_2025_a01', 2025, 'ethics_pyq_2025', 'A', 'medium', 'Discuss the ethical dimensions of social media use in the context of mental health, particularly among youth. How should civil servants address this challenge?', None, None, 10, 'pyq', '["digital_ethics", "civil_service_values"]', '[]', 'IDEA-U', 1, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a02', 2025, 'ethics_pyq_2025', 'A', 'medium', 'What is constitutional morality? How does it differ from popular morality and why is it essential for a democratic polity?', None, None, 10, 'pyq', '["constitutional_morality", "governance"]', '["ambedkar"]', 'IDEA-U', 2, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a03', 2025, 'ethics_pyq_2025', 'A', 'medium', 'Clausewitz said war is the continuation of politics by other means. Examine the ethical limits of this doctrine in the context of modern statecraft.', None, None, 10, 'pyq', '["international_ethics", "governance"]', '[]', 'IDEA-U', 3, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a04', 2025, 'ethics_pyq_2025', 'A', 'medium', 'How should the government compensate communities displaced by eco-sensitive zone notifications? Examine the ethical tensions between environmental protection and livelihood rights.', None, None, 10, 'pyq', '["environmental_ethics", "governance"]', '[]', 'IDEA-U', 4, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a05', 2025, 'ethics_pyq_2025', 'A', 'medium', 'Thiruvalluvar in Tirukkural emphasizes the virtues of righteous conduct and wisdom. How are these values relevant to contemporary public administration?', None, None, 10, 'pyq', '["civil_service_values", "integrity"]', '["thiruvalluvar"]', 'IDEA-U', 5, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a06', 2025, 'ethics_pyq_2025', 'A', 'medium', 'William James argued that belief shapes reality. How does this pragmatist view apply to the ethical foundations of public policy making?', None, None, 10, 'pyq', '["governance", "civil_service_values"]', '[]', 'IDEA-U', 6, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a07', 2025, 'ethics_pyq_2025', 'A', 'medium', 'Vivekananda believed that service to man is service to God. How does this philosophy translate into the ethic of public service in modern India?', None, None, 10, 'pyq', '["civil_service_values", "integrity"]', '["vivekananda"]', 'IDEA-U', 7, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a08', 2025, 'ethics_pyq_2025', 'A', 'medium', "Objectivity and impartiality are foundational to a civil servant's role. But in situations of moral distress, how should a civil servant balance objectivity with ethical sensitivity?", None, None, 10, 'pyq', '["civil_service_values", "emotional_intelligence"]', '[]', 'IDEA-U', 8, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a09', 2025, 'ethics_pyq_2025', 'A', 'medium', 'Mahavira taught the principle of non-possessiveness (aparigraha). How is this value relevant in addressing corruption and consumerism in public life?', None, None, 10, 'pyq', '["integrity", "corruption"]', '["mahavira"]', 'IDEA-U', 9, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a10', 2025, 'ethics_pyq_2025', 'A', 'medium', 'The Bhagavad Gita advocates nishkama karma — action without attachment to results. How can this philosophy guide ethical decision-making in public administration?', None, None, 10, 'pyq', '["civil_service_values", "integrity"]', '[]', 'IDEA-U', 10, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a11', 2025, 'ethics_pyq_2025', 'A', 'medium', 'A civil servant is expected to be a facilitator, not just a regulator. Examine this shift in role and its ethical implications.', None, None, 10, 'pyq', '["civil_service_values", "governance"]', '[]', 'IDEA-U', 11, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a12', 2025, 'ethics_pyq_2025', 'A', 'medium', 'How can organizations cultivate a culture of workplace ethics? What is the role of leadership in sustaining ethical norms within public institutions?', None, None, 10, 'pyq', '["governance", "civil_service_values", "integrity"]', '[]', 'IDEA-U', 12, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_a13', 2025, 'ethics_pyq_2025', 'A', 'medium', 'What ethical frameworks can guide sustainable economic growth? Critically examine how these frameworks can be integrated into national policy.', None, None, 10, 'pyq', '["environmental_ethics", "governance"]', '[]', 'IDEA-U', 13, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b01_ctx', 2025, 'ethics_pyq_2025', 'B', 'case_study', '(Context — see sub-parts below)', 'Vijay is a Deputy Commissioner supervising a live disaster relief operation when he receives news that his mother has died. His team is in the critical phase of rescue. He must decide whether to leave or stay.', None, 0, 'pyq', '["duty_vs_personal"]', '[]', 'STAKE', 14, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b01_a', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'What are the ethical issues Vijay faces in this situation?', None, 'a', 8, 'pyq', '["duty_vs_personal", "civil_service_values"]', '[]', 'STAKE', 15, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b01_b', 2025, 'ethics_pyq_2025', 'B', 'case_study', "What would you do in Vijay's place and why?", None, 'b', 12, 'pyq', '["duty_vs_personal", "civil_service_values"]', '[]', 'STAKE', 16, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b02_ctx', 2025, 'ethics_pyq_2025', 'B', 'case_study', '(Context — see sub-parts below)', "A District Administration is under pressure from the state government to clear a notified forest area for a low-cost housing project. The DM knows that this will displace hundreds of tribal families and damage a critical ecological zone, but the project is backed by the Chief Minister's office.", None, 0, 'pyq', '["development_environment"]', '[]', 'STAKE', 17, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b02_a', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'Identify the stakeholders and the ethical tensions in this case.', None, 'a', 8, 'pyq', '["development_environment", "environmental_ethics", "governance"]', '[]', 'STAKE', 18, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b02_b', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'What course of action would you take as the DM, and what ethical principles guide your decision?', None, 'b', 12, 'pyq', '["development_environment", "civil_service_values", "integrity"]', '[]', 'STAKE', 19, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b03_ctx', 2025, 'ethics_pyq_2025', 'B', 'case_study', '(Context — see sub-parts below)', "Subash is Principal Secretary, PWD. A major infrastructure contract is to be awarded. His son's firm is one of the bidders. A minister also informally recommends another firm whose owner is his nephew. Subash must ensure transparency and fairness in the tender process.", None, 0, 'pyq', '["conflict_of_interest"]', '[]', 'STAKE', 20, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b03_a', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'What are the ethical issues involved in this scenario?', None, 'a', 8, 'pyq', '["conflict_of_interest", "integrity", "governance"]', '[]', 'STAKE', 21, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b03_b', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'As Subash, what steps would you take to ensure the integrity of the procurement process?', None, 'b', 12, 'pyq', '["conflict_of_interest", "civil_service_values", "transparency"]', '[]', 'STAKE', 22, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b04_ctx', 2025, 'ethics_pyq_2025', 'B', 'case_study', '(Context — see sub-parts below)', 'Rajesh is Administrator in a PSU. His boss pressures him to approve a purchase order that bypasses standard procurement norms, claiming urgency. Rajesh suspects the vendor has a kickback arrangement with his boss. Refusing could harm his career; complying would breach procedure and public trust.', None, 0, 'pyq', '["hierarchical_pressure", "corruption_misuse"]', '[]', 'STAKE', 23, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b04_a', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'What are the ethical dimensions of the dilemma Rajesh faces?', None, 'a', 8, 'pyq', '["hierarchical_pressure", "corruption", "integrity"]', '[]', 'STAKE', 24, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b04_b', 2025, 'ethics_pyq_2025', 'B', 'case_study', "What would you do in Rajesh's position? Justify your course of action.", None, 'b', 12, 'pyq', '["hierarchical_pressure", "civil_service_values", "corruption"]', '[]', 'STAKE', 25, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b05_ctx', 2025, 'ethics_pyq_2025', 'B', 'case_study', '(Context — see sub-parts below)', 'A District Admin audit reveals that MGNREGA funds in three blocks have been siphoned through ghost workers and fake muster rolls. The block-level officers, local politicians, and some panchayat officials appear to be involved. The DM faces resistance when trying to investigate, with political interference from multiple levels.', None, 0, 'pyq', '["corruption_misuse"]', '[]', 'STAKE', 26, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b05_a', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'Identify the ethical issues and stakeholders involved in this case.', None, 'a', 8, 'pyq', '["corruption", "governance", "whistleblowing"]', '[]', 'STAKE', 27, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b05_b', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'As the DM, what institutional and procedural steps would you take to address this fraud while protecting yourself and the genuine workers?', None, 'b', 12, 'pyq', '["corruption", "civil_service_values", "transparency", "integrity"]', '[]', 'STAKE', 28, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b06_ctx', 2025, 'ethics_pyq_2025', 'B', 'case_study', '(Context — see sub-parts below)', 'Ashok is Divisional Commissioner of a border district. A sudden storm traps over 200 civilians — including foreign nationals — on the Indian side of a disputed border area. Providing emergency shelter and relief would mean temporarily settling civilians in a restricted military zone, which requires clearances Ashok cannot quickly obtain. Delaying risks lives.', None, 0, 'pyq', '["disaster_allocation", "international_ethics"]', '[]', 'STAKE', 29, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b06_a', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'What are the ethical and legal dilemmas Ashok faces in this situation?', None, 'a', 8, 'pyq', '["disaster_allocation", "international_ethics", "governance"]', '[]', 'STAKE', 30, '2026-06-21 13:30:49'),
        ('ethics_pyq_2025_b06_b', 2025, 'ethics_pyq_2025', 'B', 'case_study', 'What decision would you take as Ashok and on what ethical grounds?', None, 'b', 12, 'pyq', '["disaster_allocation", "civil_service_values", "conscience"]', '[]', 'STAKE', 31, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a01', 2026, 'ethics_prac_1', 'A', 'medium', 'What is integrity in public life? How does it differ from mere rule-following?', None, None, 10, 'practice', '["integrity"]', '[]', 'IDEA-U', 1, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a02', 2026, 'ethics_prac_1', 'A', 'medium', 'Define emotional intelligence. How does it enhance the effectiveness of a civil servant?', None, None, 10, 'practice', '["emotional_intelligence"]', '[]', 'IDEA-U', 2, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a03', 2026, 'ethics_prac_1', 'A', 'medium', 'Examine the relevance of the teachings of Gandhi, Vivekananda and Chanakya for ethical governance in modern India.', None, None, 10, 'practice', '["civil_service_values", "governance"]', '["gandhi", "vivekananda", "chanakya"]', 'IDEA-U', 3, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a04', 2026, 'ethics_prac_1', 'A', 'medium', 'What is constitutional morality? Why did Ambedkar consider it more important than social morality?', None, None, 10, 'practice', '["constitutional_morality"]', '["ambedkar"]', 'IDEA-U', 4, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a05', 2026, 'ethics_prac_1', 'A', 'medium', 'Examine the ethical challenges posed by artificial intelligence and social media in public administration.', None, None, 10, 'practice', '["digital_ethics"]', '[]', 'IDEA-U', 5, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a06', 2026, 'ethics_prac_1', 'A', 'medium', 'How does Mission Karmayogi seek to inculcate ethics in civil servants? Critically evaluate.', None, None, 10, 'practice', '["civil_service_values", "governance"]', '[]', 'IDEA-U', 6, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a07', 2026, 'ethics_prac_1', 'A', 'medium', 'What are the ethical obligations of a civil servant when faced with orders that conflict with law?', None, None, 10, 'practice', '["laws_ethics", "conscience"]', '[]', 'IDEA-U', 7, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a08', 2026, 'ethics_prac_1', 'A', 'medium', 'Distinguish between attitude and aptitude. Which is more important for a civil servant and why?', None, None, 10, 'practice', '["aptitude"]', '[]', 'IDEA-U', 8, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a09', 2026, 'ethics_prac_1', 'A', 'medium', 'What is conflict of interest? How should public servants manage it to maintain impartiality?', None, None, 10, 'practice', '["conflict_of_interest"]', '[]', 'IDEA-U', 9, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a10', 2026, 'ethics_prac_1', 'A', 'medium', 'Explain the concept of emotional objectivity in civil service. How does it balance empathy with impartiality?', None, None, 10, 'practice', '["emotional_intelligence", "aptitude"]', '[]', 'IDEA-U', 10, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a11', 2026, 'ethics_prac_1', 'A', 'medium', 'What is the relationship between personal ethics and professional ethics in public service?', None, None, 10, 'practice', '["integrity", "civil_service_values"]', '[]', 'IDEA-U', 11, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a12', 2026, 'ethics_prac_1', 'A', 'medium', 'How can RTI and whistleblower protection mechanisms strengthen ethical governance?', None, None, 10, 'practice', '["transparency", "corruption"]', '[]', 'IDEA-U', 12, '2026-06-21 13:30:49'),
        ('ethics_prac_1_a13', 2026, 'ethics_prac_1', 'A', 'medium', 'Examine the ethical dimensions of environmental governance in the context of sustainable development goals.', None, None, 10, 'practice', '["environmental_ethics", "governance"]', '[]', 'IDEA-U', 13, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b01_ctx', 2026, 'ethics_prac_1', 'B', 'case_study', '(Context — see sub-parts below)', 'Priya is a District Collector. Her senior officer pressures her to approve a sub-standard road construction contract, suggesting the funds will partly finance an upcoming party election campaign. She has evidence of inflated bills and knows approving the contract would harm public interest.', None, 0, 'practice', '["hierarchical_pressure", "corruption_misuse"]', '[]', 'STAKE', 14, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b01_a', 2026, 'ethics_prac_1', 'B', 'case_study', 'What are the ethical issues and conflicts Priya faces?', None, 'a', 8, 'practice', '["hierarchical_pressure", "corruption", "integrity"]', '[]', 'STAKE', 15, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b01_b', 2026, 'ethics_prac_1', 'B', 'case_study', "What steps would you take in Priya's position to uphold public interest without endangering your career?", None, 'b', 12, 'practice', '["hierarchical_pressure", "civil_service_values", "whistleblowing"]', '[]', 'STAKE', 16, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b02_ctx', 2026, 'ethics_prac_1', 'B', 'case_study', '(Context — see sub-parts below)', 'Arvind, a mid-level officer in the Pollution Control Board, discovers that a large industrial unit is illegally dumping toxic effluents into a river used by downstream villages for drinking water. His Board Chairman is known to have ties with the industry and has warned officers not to act without his clearance.', None, 0, 'practice', '["whistleblowing"]', '[]', 'STAKE', 17, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b02_a', 2026, 'ethics_prac_1', 'B', 'case_study', 'What are the ethical and institutional dilemmas Arvind faces?', None, 'a', 8, 'practice', '["whistleblowing", "corruption", "environmental_ethics"]', '[]', 'STAKE', 18, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b02_b', 2026, 'ethics_prac_1', 'B', 'case_study', 'What course of action would you recommend for Arvind? Justify with ethical reasoning.', None, 'b', 12, 'practice', '["whistleblowing", "civil_service_values", "integrity"]', '[]', 'STAKE', 19, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b03_ctx', 2026, 'ethics_prac_1', 'B', 'case_study', '(Context — see sub-parts below)', 'Meera is a Block Development Officer managing a flood relief camp. On the third day of the operation, she receives news that her elderly father has suffered a serious stroke and is alone at home 150 km away. The camp is at a critical stage and her deputy has limited experience.', None, 0, 'practice', '["duty_vs_personal"]', '[]', 'STAKE', 20, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b03_a', 2026, 'ethics_prac_1', 'B', 'case_study', 'What competing moral obligations does Meera face? How would you analyse these using ethical frameworks?', None, 'a', 10, 'practice', '["duty_vs_personal", "emotional_intelligence"]', '[]', 'STAKE', 21, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b03_b', 2026, 'ethics_prac_1', 'B', 'case_study', "What decision would you take in Meera's place and how would you execute it?", None, 'b', 10, 'practice', '["duty_vs_personal", "civil_service_values"]', '[]', 'STAKE', 22, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b04_ctx', 2026, 'ethics_prac_1', 'B', 'case_study', '(Context — see sub-parts below)', 'A District Social Welfare Officer discovers that a family genuinely eligible for a subsidised housing scheme is being denied because of a minor documentation gap. The rules are explicit: no exceptions. Neighbouring officers have bent the rules for politically connected applicants while denying genuine poor families.', None, 0, 'practice', '["rules_vs_compassion"]', '[]', 'STAKE', 23, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b04_a', 2026, 'ethics_prac_1', 'B', 'case_study', 'What are the ethical tensions in applying rules strictly when they produce unjust outcomes?', None, 'a', 10, 'practice', '["rules_vs_compassion", "laws_ethics", "conscience"]', '[]', 'STAKE', 24, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b04_b', 2026, 'ethics_prac_1', 'B', 'case_study', 'What would you do as the Welfare Officer? What systemic changes would you recommend?', None, 'b', 10, 'practice', '["rules_vs_compassion", "governance", "civil_service_values"]', '[]', 'STAKE', 25, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b05_ctx', 2026, 'ethics_prac_1', 'B', 'case_study', '(Context — see sub-parts below)', 'The government proposes to acquire land from five villages to build a highway. The villages have subsisted on this land for generations. The district administration, including you as DM, must conduct consultations. Tribal leaders are opposed, but the project is classified as a national priority and the state government is under pressure to deliver.', None, 0, 'practice', '["development_environment"]', '[]', 'STAKE', 26, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b05_a', 2026, 'ethics_prac_1', 'B', 'case_study', 'Analyse the ethical dimensions of development-induced displacement and the rights of affected communities.', None, 'a', 10, 'practice', '["development_environment", "environmental_ethics", "governance"]', '[]', 'STAKE', 27, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b05_b', 2026, 'ethics_prac_1', 'B', 'case_study', 'What process would you follow as DM to ensure a fair, ethical, and legally sound outcome?', None, 'b', 10, 'practice', '["development_environment", "civil_service_values", "integrity"]', '[]', 'STAKE', 28, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b06_ctx', 2026, 'ethics_prac_1', 'B', 'case_study', '(Context — see sub-parts below)', 'Sunita is a Section Officer in a government office. A female colleague confides in her that the Joint Secretary has been making inappropriate comments and creating a hostile work environment. The colleague is reluctant to file a formal complaint fearing professional consequences. Sunita is the Internal Complaints Committee convenor.', None, 0, 'practice', '["gender_discrimination"]', '[]', 'STAKE', 29, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b06_a', 2026, 'ethics_prac_1', 'B', 'case_study', 'What are the ethical obligations of Sunita in her dual role as colleague and ICC convenor?', None, 'a', 10, 'practice', '["gender_discrimination", "civil_service_values", "integrity"]', '[]', 'STAKE', 30, '2026-06-21 13:30:49'),
        ('ethics_prac_1_b06_b', 2026, 'ethics_prac_1', 'B', 'case_study', 'What steps would you take as Sunita to protect your colleague, uphold procedure, and ensure justice without coercion?', None, 'b', 10, 'practice', '["gender_discrimination", "governance", "conscience"]', '[]', 'STAKE', 31, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a01', 2026, 'ethics_prac_2', 'A', 'medium', "The Dalai Lama said: 'If you think you are too small to make a difference, try sleeping with a mosquito.' How does this metaphor apply to individual ethical responsibility in public institutions?", None, None, 10, 'practice', '["integrity", "civil_service_values"]', '[]', 'IDEA-U', 1, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a02', 2026, 'ethics_prac_2', 'A', 'medium', "Thiruvalluvar wrote: 'Whatever the source, water takes the colour of the soil.' Examine this idea in the context of organisational culture and ethical behaviour of civil servants.", None, None, 10, 'practice', '["civil_service_values", "governance"]', '["thiruvalluvar"]', 'IDEA-U', 2, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a03', 2026, 'ethics_prac_2', 'A', 'medium', "William James said: 'Act as if what you do makes a difference. It does.' How does pragmatist ethics differ from deontological and consequentialist approaches in guiding public administration?", None, None, 10, 'practice', '["governance", "civil_service_values"]', '[]', 'IDEA-U', 3, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a04', 2026, 'ethics_prac_2', 'A', 'medium', 'Distinguish between attitude and aptitude with examples. How does Mission Karmayogi address both in building ethical civil servants?', None, None, 10, 'practice', '["aptitude", "civil_service_values"]', '[]', 'IDEA-U', 4, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a05', 2026, 'ethics_prac_2', 'A', 'medium', 'How do CSR obligations of corporations extend beyond profit? Examine the ethical basis of corporate accountability to society.', None, None, 10, 'practice', '["governance", "international_ethics"]', '[]', 'IDEA-U', 5, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a06', 2026, 'ethics_prac_2', 'A', 'medium', "What ethical principles should govern India's foreign policy decisions, particularly in humanitarian crises abroad?", None, None, 10, 'practice', '["international_ethics", "governance"]', '[]', 'IDEA-U', 6, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a07', 2026, 'ethics_prac_2', 'A', 'medium', "Discuss the ethical dimensions of data privacy in the age of digital governance. How should the state balance surveillance with citizens' rights?", None, None, 10, 'practice', '["digital_ethics", "governance"]', '[]', 'IDEA-U', 7, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a08', 2026, 'ethics_prac_2', 'A', 'medium', "Chanakya's Arthashastra endorses deception for the state's welfare. Examine how this Realist view conflicts with modern democratic ethics.", None, None, 10, 'practice', '["governance", "international_ethics"]', '["chanakya"]', 'IDEA-U', 8, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a09', 2026, 'ethics_prac_2', 'A', 'medium', 'What is the role of conscience in ethical decision-making? Is a guilty conscience a reliable moral guide for a public servant?', None, None, 10, 'practice', '["conscience", "integrity"]', '[]', 'IDEA-U', 9, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a10', 2026, 'ethics_prac_2', 'A', 'medium', 'Why is emotional intelligence considered more critical than technical expertise for senior civil servants? Illustrate with examples.', None, None, 10, 'practice', '["emotional_intelligence", "civil_service_values"]', '[]', 'IDEA-U', 10, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a11', 2026, 'ethics_prac_2', 'A', 'medium', 'What is the relationship between gender equality and good governance? How can public institutions embed gender ethics into their processes?', None, None, 10, 'practice', '["gender_equality", "governance"]', '[]', 'IDEA-U', 11, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a12', 2026, 'ethics_prac_2', 'A', 'medium', 'Examine the tension between laws and ethics using examples from Indian governance where legal actions were ethical violations or vice versa.', None, None, 10, 'practice', '["laws_ethics", "conscience", "governance"]', '[]', 'IDEA-U', 12, '2026-06-21 13:30:49'),
        ('ethics_prac_2_a13', 2026, 'ethics_prac_2', 'A', 'medium', 'How does corruption erode the moral fabric of public institutions? Suggest both systemic and individual-level measures to combat it.', None, None, 10, 'practice', '["corruption", "integrity", "transparency"]', '[]', 'IDEA-U', 13, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b01_ctx', 2026, 'ethics_prac_2', 'B', 'case_study', '(Context — see sub-parts below)', "Ratan is a senior engineer in a government infrastructure project. His department head is also the contractor's brother-in-law and insists on approving the contractor's inflated final bill. Separately, the same contractor has offered Ratan's son a well-paying job after his graduation. Ratan must sign the bill approval.", None, 0, 'practice', '["conflict_of_interest"]', '[]', 'STAKE', 14, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b01_a', 2026, 'ethics_prac_2', 'B', 'case_study', 'Identify all the conflict-of-interest layers in this case and their ethical implications.', None, 'a', 8, 'practice', '["conflict_of_interest", "integrity", "corruption"]', '[]', 'STAKE', 15, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b01_b', 2026, 'ethics_prac_2', 'B', 'case_study', 'What would you do as Ratan? How would you document your decision to protect yourself?', None, 'b', 12, 'practice', '["conflict_of_interest", "civil_service_values", "transparency"]', '[]', 'STAKE', 16, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b02_ctx', 2026, 'ethics_prac_2', 'B', 'case_study', '(Context — see sub-parts below)', 'A flash flood has damaged three villages. The State Disaster Management Authority has sent limited supplies — medicines, food, and clean water — enough for only one village for 48 hours. You are the nodal officer on the ground. Village A has the largest population including many elderly. Village B has a maternity clinic with high-risk pregnancies. Village C is the most inaccessible and may be cut off entirely if another flood comes.', None, 0, 'practice', '["disaster_allocation"]', '[]', 'STAKE', 17, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b02_a', 2026, 'ethics_prac_2', 'B', 'case_study', 'What ethical frameworks are most relevant to triage decisions in disaster relief? How do they conflict here?', None, 'a', 10, 'practice', '["disaster_allocation", "governance"]', '[]', 'STAKE', 18, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b02_b', 2026, 'ethics_prac_2', 'B', 'case_study', 'How would you allocate resources and what steps would you take to obtain additional supplies urgently?', None, 'b', 10, 'practice', '["disaster_allocation", "civil_service_values", "conscience"]', '[]', 'STAKE', 19, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b03_ctx', 2026, 'ethics_prac_2', 'B', 'case_study', '(Context — see sub-parts below)', "A multinational pharma company exports a drug to developing countries at a 40% lower quality standard than the version sold in Europe, exploiting the absence of stringent regulation in those markets. An Indian quality inspector working in the company's Indian subsidiary discovers this discrepancy in a batch destined for Sub-Saharan Africa.", None, 0, 'practice', '["private_sector", "international_ethics"]', '[]', 'STAKE', 20, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b03_a', 2026, 'ethics_prac_2', 'B', 'case_study', 'What are the ethical issues raised by differential quality standards for products sold in rich vs poor countries?', None, 'a', 10, 'practice', '["private_sector", "international_ethics", "governance"]', '[]', 'STAKE', 21, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b03_b', 2026, 'ethics_prac_2', 'B', 'case_study', 'What steps should the inspector take, and what protections does Indian law offer a private sector whistleblower?', None, 'b', 10, 'practice', '["whistleblowing", "private_sector", "integrity"]', '[]', 'STAKE', 22, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b04_ctx', 2026, 'ethics_prac_2', 'B', 'case_study', '(Context — see sub-parts below)', 'You are posted as Deputy Commissioner of a border district. A group of 300 refugees from a neighbouring country have crossed into India fleeing communal violence. They have no documents. Local villagers are sympathetic but politicians are demanding their immediate deportation, citing national security. International humanitarian law and Indian domestic law point in conflicting directions.', None, 0, 'practice', '["international_ethics", "disaster_allocation"]', '[]', 'STAKE', 23, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b04_a', 2026, 'ethics_prac_2', 'B', 'case_study', 'What are the ethical dimensions of this humanitarian crisis from both national and international perspectives?', None, 'a', 10, 'practice', '["international_ethics", "governance", "conscience"]', '[]', 'STAKE', 24, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b04_b', 2026, 'ethics_prac_2', 'B', 'case_study', 'What immediate and medium-term steps would you take as DC, balancing security concerns with humanitarian obligations?', None, 'b', 10, 'practice', '["international_ethics", "civil_service_values", "laws_ethics"]', '[]', 'STAKE', 25, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b05_ctx', 2026, 'ethics_prac_2', 'B', 'case_study', '(Context — see sub-parts below)', 'A CAG team auditing MGNREGA in your district finds massive irregularities: 40% of job cards belong to non-existent workers, and payment records show transfers to ghost accounts. The audit is ongoing. Your predecessor (now a senior officer in the state government) appears to have signed off on many of the fraudulent muster rolls.', None, 0, 'practice', '["corruption_misuse", "whistleblowing"]', '[]', 'STAKE', 26, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b05_a', 2026, 'ethics_prac_2', 'B', 'case_study', "What are the ethical challenges you face as the sitting DM when a predecessor's misconduct is uncovered under your watch?", None, 'a', 10, 'practice', '["corruption", "integrity", "laws_ethics"]', '[]', 'STAKE', 27, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b05_b', 2026, 'ethics_prac_2', 'B', 'case_study', 'How would you cooperate with the audit, protect genuine workers, and ensure accountability without exceeding your jurisdiction?', None, 'b', 10, 'practice', '["corruption", "civil_service_values", "governance"]', '[]', 'STAKE', 28, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b06_ctx', 2026, 'ethics_prac_2', 'B', 'case_study', '(Context — see sub-parts below)', "A critically ill patient brought to a government hospital needs a blood transfusion urgently. The required blood group is unavailable in the hospital blood bank. A private lab nearby has the blood but will not release it without full advance payment, which the patient's family cannot afford. The hospital's emergency fund is locked pending a finance department approval that takes 72 hours. The patient has hours.", None, 0, 'practice', '["rules_vs_compassion"]', '[]', 'STAKE', 29, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b06_a', 2026, 'ethics_prac_2', 'B', 'case_study', 'What ethical principles are in tension in this case? How do bureaucratic procedures conflict with the right to life?', None, 'a', 10, 'practice', '["rules_vs_compassion", "laws_ethics", "conscience"]', '[]', 'STAKE', 30, '2026-06-21 13:30:49'),
        ('ethics_prac_2_b06_b', 2026, 'ethics_prac_2', 'B', 'case_study', 'As the Medical Superintendent on duty, what would you do immediately, and what systemic reforms would you recommend to prevent this situation?', None, 'b', 10, 'practice', '["rules_vs_compassion", "civil_service_values", "governance"]', '[]', 'STAKE', 31, '2026-06-21 13:30:49'),
        ]
    )

    conn.commit()
