"""
Prototype diagram rendering test — v2.
Shows the new approach side by side:
  Flowchart  → Mermaid (CDN, already working)
  Curve      → matplotlib standard diagram (offline, no AI generation)
  Table      → HTML (fixed fence stripping)
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
import streamlit as st
from styles import apply_theme
from diagrams import (
    draw_demand_supply, draw_is_lm, draw_phillips_curve,
    draw_indifference_curve, draw_production_function,
    draw_solow_model, draw_lorenz_curve, draw_isoquant,
    COVERED_TYPES,
)
from table_renderer import render_table

st.set_page_config(page_title="Diagram Prototype Test v2", layout="wide", page_icon="🧪")
apply_theme()

st.markdown("## 🧪 Diagram Prototype — v2 (New Approach)")
st.markdown(
    '<div style="font-size:0.85rem;color:#9AA0A6;margin-bottom:4px">'
    'Approach: Flowcharts → Mermaid (AI-generated) · Curves → Standard matplotlib (pre-coded) · Tables → HTML</div>'
    '<div style="font-size:0.82rem;color:#9AA0A6;margin-bottom:20px">'
    'Standard diagrams show the canonical textbook concept. Student adjusts to specific question values.</div>',
    unsafe_allow_html=True,
)

# ── Section 1: Mermaid Flowchart (already working from v1) ───────────────────

st.markdown("---")
st.markdown("### 🔷 Flowchart — Mermaid (AI-generated from description)")
st.markdown(
    '<div class="gem-card" style="margin-bottom:8px">'
    '<span style="font-size:0.75rem;color:#9AA0A6">Question: </span>'
    '<span style="font-size:0.88rem;color:#E8EAED">'
    'State and prove the Stolper-Samuelson Theorem in international trade. What is the magnification effect?'
    '</span></div>',
    unsafe_allow_html=True,
)

# Load flowchart code from prototype JSON (generated by prototype_diagrams.py)
data_path = Path(__file__).parent.parent.parent / "exports" / "prototype_diagrams.json"
flowchart_code = None
html_table_code = None

if data_path.exists():
    prototypes = json.loads(data_path.read_text())
    for p in prototypes:
        if p["diagram_format"] == "mermaid":
            flowchart_code = p["generated_code"]
        elif p["diagram_format"] == "html":
            raw = p["generated_code"].strip()
            # Strip markdown fences if model added them (```html ... ```)
            if raw.startswith("```"):
                lines = raw.split("\n")
                lines = [l for l in lines if not l.strip().startswith("```")]
                raw = "\n".join(lines).strip()
            html_table_code = raw

col1, col2 = st.columns([3, 2])
with col1:
    if flowchart_code:
        mermaid_html = f"""
        <div style="background:#1C1C1E;padding:16px;border-radius:8px">
            <pre class="mermaid" style="background:transparent;color:#E8EAED">
{flowchart_code}
            </pre>
        </div>
        <script type="module">
          import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
          mermaid.initialize({{ startOnLoad: true, theme: 'dark' }});
        </script>
        """
        st.components.v1.html(mermaid_html, height=450, scrolling=True)
    else:
        st.warning("Run `python3 scripts/prototype_diagrams.py` first to generate flowchart code.")
with col2:
    st.markdown(
        '<div style="font-size:0.8rem;color:#81C995;margin-bottom:8px">✅ Status: Working</div>',
        unsafe_allow_html=True,
    )
    st.markdown("Mermaid flowcharts render cleanly. Needs internet for the CDN renderer (one-time load).")
    if flowchart_code:
        st.code(flowchart_code, language="text")


# ── Section 2: Standard matplotlib diagrams ────────────────────────────────────

st.markdown("---")
st.markdown("### 📈 Standard Curves — Pre-coded matplotlib diagrams")
st.markdown(
    '<div style="font-size:0.82rem;color:#9AA0A6;margin-bottom:16px">'
    'These are drawn from code, not AI generation. Each is the canonical textbook version. '
    'No API calls. No internet required. Works offline permanently.</div>',
    unsafe_allow_html=True,
)

diagram_showcase = [
    ("Demand-Supply Curve (standard + shift)", draw_demand_supply, {"shifted": True}),
    ("Demand-Supply Curve (standard, no shift)", draw_demand_supply, {}),
    ("IS-LM Model", draw_is_lm, {}),
    ("IS-LM with Fiscal Expansion", draw_is_lm, {"fiscal_shift": True}),
    ("Phillips Curve (SRPC + LRPC)", draw_phillips_curve, {}),
    ("Indifference Curve Analysis", draw_indifference_curve, {}),
    ("Production Function (TP, AP, MP)", draw_production_function, {}),
    ("Solow Growth Model", draw_solow_model, {}),
    ("Lorenz Curve (High Inequality)", draw_lorenz_curve, {"gini_level": "high"}),
    ("Lorenz Curve (Low Inequality)", draw_lorenz_curve, {"gini_level": "low"}),
    ("Isoquant-Isocost Analysis", draw_isoquant, {}),
]

cols = st.columns(2)
for i, (label, fn, kwargs) in enumerate(diagram_showcase):
    with cols[i % 2]:
        st.markdown(f'<div style="font-size:0.8rem;color:#8AB4F8;margin:8px 0 4px;font-weight:600">{label}</div>',
                    unsafe_allow_html=True)
        try:
            fig = fn(**kwargs)
            st.pyplot(fig)
            import matplotlib.pyplot as plt
            plt.close(fig)
        except Exception as e:
            st.error(f"Error: {e}")


# ── Section 3: HTML Table ──────────────────────────────────────────────────────

st.markdown("---")
st.markdown("### 📊 Comparison Table — HTML (AI-generated, fixed fence stripping)")
st.markdown(
    '<div class="gem-card" style="margin-bottom:8px">'
    '<span style="font-size:0.75rem;color:#9AA0A6">Question: </span>'
    '<span style="font-size:0.88rem;color:#E8EAED">'
    'Distinguish between internal and external public debt. Explain the debate on burden of public debt.'
    '</span></div>',
    unsafe_allow_html=True,
)

col3, col4 = st.columns([3, 2])
# Hardcoded 3 sample table descriptions to show all formats
SAMPLE_TABLES = [
    {
        "label": "Format A — Pipe-separated rows (most common)",
        "desc": """Comparative Table — Internal vs External Public Debt Burden

Columns: [Dimension | Internal Public Debt | External Public Debt]
Rows:
1. Source of funds | Domestic residents, banks, RBI | Foreign governments, multilateral agencies, ECBs
2. Currency denomination | Indian Rupee (₹) | Primarily USD (54.2%), Euro, SDR
3. Nature of burden | Transfer payment (redistribution within nation) | Real resource outflow (genuine burden on national economy)
4. Crowding-out risk | High — competes with private sector for loanable funds | Moderate — adds forex demand pressure
5. Sovereignty risk | Nil | High — conditionalities possible (IMF, World Bank)
6. Key instruments | G-Secs, T-Bills, dated securities | ECBs, Masala Bonds, multilateral loans

Key analytical point: Classical economists treated internal debt as no burden; external debt always constitutes real burden. Ricardian Equivalence and Domar's g>r condition qualify both positions.""",
    },
    {
        "label": "Format B — 'Row N: val | val' (FRBM style)",
        "desc": """TABLE TITLE: Key FRBM Fiscal Targets vs. Actuals

Columns: [Fiscal Indicator | FRBM Target | Actual FY 2022-23 | Compliance Status]

Row 1: State Fiscal Deficit | ≤3% of GSDP | ~3.4% (aggregate average) | Breached in multiple states
Row 2: Revenue Deficit | 0% (complete elimination) | Positive deficit in ~10 states | Partially complied
Row 3: General Government Debt | ≤60% of GDP by FY25 | 81.35% of GDP | Significantly exceeded
Row 4: Interest Payments as % of Revenue | ≤15% | Exceeds 20% in stressed states | Critical concern

Interpretation: Sub-national fiscal discipline remains incomplete; debt-to-GDP ratio is the most critical deviation.""",
    },
    {
        "label": "Format C — 2×2 Classification matrix",
        "desc": """A 2×2 classification table with rows representing Rivalry (Rival / Non-Rival) and columns representing Excludability (Excludable / Non-Excludable). Cell 1 (Rival + Excludable): Private Goods (e.g., food, clothing). Cell 2 (Rival + Non-Excludable): Common Resources / Open-Access Goods (e.g., fisheries). Cell 3 (Non-Rival + Excludable): Club Goods (e.g., toll roads, cable TV). Cell 4 (Non-Rival + Non-Excludable): Pure Public Goods (e.g., national defense, street lights). This matrix clearly distinguishes public goods from private goods.""",
    },
]

with col3:
    for sample in SAMPLE_TABLES:
        st.markdown(
            f'<div style="font-size:0.78rem;color:#8AB4F8;font-weight:600;margin:12px 0 4px">'
            f'{sample["label"]}</div>', unsafe_allow_html=True
        )
        st.markdown(render_table(sample["desc"]), unsafe_allow_html=True)

with col4:
    st.markdown('<div style="font-size:0.8rem;color:#81C995;margin-bottom:8px">✅ Pure Python parser — zero AI, offline</div>',
                unsafe_allow_html=True)
    st.markdown(
        "**How it works:** A Python text parser reads the `diagram_description` and extracts "
        "column headers, row values, and footer notes — then renders as a styled HTML table. "
        "No AI calls. No internet. Works forever offline.\n\n"
        "**Coverage:** 63% of 103 table descriptions parse as proper HTML tables. "
        "Remaining 37% display as clean preformatted text (no broken UI)."
    )

# ── Coverage summary ───────────────────────────────────────────────────────────

st.markdown("---")
st.markdown("### 📊 Coverage with new approach")
coverage_data = {
    "Flowchart (Mermaid)": ("347 diagrams", "✅ AI-generated Mermaid code · requires internet once"),
    "Demand-Supply curves": ("167 diagrams", "✅ Standard matplotlib · offline"),
    "Comparison tables": ("103 diagrams", "✅ AI-generated HTML · offline after generation"),
    "Growth models (Solow)": ("43 diagrams", "✅ Standard matplotlib · offline"),
    "Indifference curves": ("36 diagrams", "✅ Standard matplotlib · offline"),
    "Production functions": ("25 diagrams", "✅ Standard matplotlib · offline"),
    "IS-LM curves": ("21 diagrams", "✅ Standard matplotlib · offline"),
    "Phillips curves": ("15 diagrams", "✅ Standard matplotlib · offline"),
    "Lorenz curves": ("15 diagrams", "✅ Standard matplotlib · offline"),
    "Isoquants": ("1 diagram", "✅ Standard matplotlib · offline"),
    "Bar charts / Scatter plots": ("161 diagrams", "⚠️ Needs data — text description retained"),
    "Other / mixed": ("159 diagrams", "⚠️ Falls back to text description"),
}

for dtype, (count, note) in coverage_data.items():
    color = "#81C995" if "✅" in note else "#FDD663"
    st.markdown(
        f'<div style="display:flex;gap:12px;padding:5px 0;border-bottom:1px solid rgba(255,255,255,0.06)">'
        f'<span style="color:{color};width:18px">{"✅" if "✅" in note else "⚠️"}</span>'
        f'<span style="color:#E8EAED;min-width:230px">{dtype}</span>'
        f'<span style="color:#9AA0A6;min-width:110px">{count}</span>'
        f'<span style="color:#9AA0A6;font-size:0.82rem">{note.replace("✅","").replace("⚠️","").strip()}</span>'
        f'</div>',
        unsafe_allow_html=True,
    )
